spring:
  application.name: BananaMusic
  profiles.active: prod

server:
  servlet.contextPath: /api
  port: 8080
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: on_param
    include-exception: true

spring.mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER

---
spring:
  sql.init.mode: always
  config.activate.on-profile: dev
  devtools.restart.enabled: true
  application:
    name: ProductsService
  datasource:
    url: "jdbc:h2:mem:productsdb"
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    defer-datasource-initialization: true
  h2:
    console.enabled: true
    console.path: /h2-ui

server:
  servlet.contextPath: /api
  port: 9090

#debug: true
logging:
  level:
    root: INFO


---
spring:
  config.activate.on-profile: prod
  application:
    name: ProductsService

  sql.init.mode: always
  devtools.restart.enabled: true
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/bananamusicdb"
    driverClassName: com.mysql.cj.jdbc.Driver
    username: banana
    password: platano
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    defer-datasource-initialization: true
    root: INFO

server:
  servlet.contextPath: /api
  port: 8443

logging:
  level:
    root: INFO